version: '3.8'

services:

  mysql-db:
    image: mysql:latest
    container_name: mysql-db-agrupado
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: PessoasDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db-agrupado
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api-mysql:
    build:
      context: ./api-mysql
    container_name: api-mysql-agrupado
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
    networks:
      - app-network

  api-mongo:
    build:
      context: ./api-mongo
    container_name: api-mongo-agrupado
    ports:
      - "8081:8080"
    depends_on:
      - mongo-db
    networks:
      - app-network

volumes:
  mysql_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
